C package simple
umarcor/ghdl-cosim pull request #7
Opened 2020-04-14 05:09 UTC by RocketRoss

As per (umarcor/ghdl-cosim/pull/4):

>Actually, you might want to keep this PR as is, and open another simpler one. 

This merely calls a packaged print function from c in 2 entities

2020-04-14 19:37 UTC, umarcor requested changes
@RocketRoss, see attached comments. Apart from those mostly style issues, the content is good. I think you can go ahead and add the corresponding reference in the docs (`doc/vhpidirect/examples/quickstart.rst`) during this iteration!

2020-04-14 19:37 UTC, umarcor commented on vhpidirect/quickstart/package/ent1.vhd
> +entity ent1 is
As commented in https://github.com/umarcor/ghdl-cosim/pull/4#discussion_r408212336, what about the following?

```vhdl
use work.pkg.c_printInt; -- can import the function only

entity ent is
end;

architecture rtl_A of ent is
begin
    process
    begin
        report "Module A calling c_print(3)." severity note;
        c_printInt(3);
        wait;        
    end process;
end;

architecture rtl_B of ent is
begin
    process
    begin
        report "Module B calling c_print(7)." severity note;
        c_printInt(7);
        wait;        
    end process;
end;
```

and

```vhdl
--use work.pkg.all; NOTE THAT IT SHOULD NOT BE REQUIRED

entity tb is
end;

architecture arch of tb is
begin

  entA : entity work.ent(rtl_A);
  entB : entity work.ent(rtl_B);

  process
  begin
    report "Testbench." severity note;
    wait;
  end process;

end;
```

2020-04-14 19:37 UTC, umarcor commented on vhpidirect/quickstart/package/pkg.vhd
> +		attribute foreign of c_printInt : procedure is "VHPIDIRECT printInt";
In other examples, the attribute is not indented with regard to the procedure. We can change it everywhere if you wish, tho. Meanwhile, let's keep it consistent.

2020-04-14 19:37 UTC, umarcor commented on vhpidirect/quickstart/package/run.sh
> +ghdl -a pkg.vhd ent1.vhd ent2.vhd tb.vhd
If entities are merged, this would be `ghdl -a pkg.vhd ent.vhd tb.vhd`.

2020-04-14 19:37 UTC, umarcor commented on vhpidirect/quickstart/package/tb.vhd
> +	end component ent2;
Tabs are used here, while spaces are used a few lines below. Please, try to keep consistency within each file. I'm ok with having some sources which use tabs only and others which use spaces only. Until we can have some pretifier/formatter for VHDL, trying to keep consistency accross all files is an imposible task. Anyway, let's try to do our best.

2020-04-14 19:37 UTC, umarcor commented on vhpidirect/quickstart/package/tb.vhd
> +use work.pkg.all;
Should not be required, since you are not using any resource from the package in this testbench.

2020-04-15 06:06 UTC, RocketRoss commented on vhpidirect/quickstart/package/tb.vhd
> +	end component ent2;
I'll double check that my Windows and Linux machines have the same configs. Of course, that was a little difficult for me to have seen. Will try keep an eye on it

2020-04-15 11:12 UTC, umarcor reviewed
I'd say that only the docs are missing!

2020-04-17 08:38 UTC, umarcor commented
@RocketRoss, I think we should prioritize this. Don't worry about the style/naming. Just add a brief description to the docs and we'll have it merged. When we are done merging this set of examples, I'll do a general check for styles...

2020-04-17 08:43 UTC, umarcor approved these changes

2020-04-17 08:43 UTC, umarcor commented on .github/workflows/test.yml
> +            quickstart/package,
Windows too...

2020-04-17 08:43 UTC, umarcor commented on doc/vhpidirect/examples/quickstart.rst
> +If the auxillary VHPIDIRECT subprograms need to be accessed in more than one entity, it is possible to package the subprograms.
Also for code reuse between different projects.

2020-04-17 08:43 UTC, umarcor commented on doc/vhpidirect/examples/quickstart.rst
> +In this example 2 different entities use a C defined ``c_printInt(val: integer)`` subprogram to print two different numbers. The subprogram attribute is declared as foreign in the ``pkg`` package and
Defining the body is a restriction explained in `COSIM:VHPIDIRECT:Declarations`.

2020-04-17 08:44 UTC, umarcor commented on .github/workflows/test.yml
> +            quickstart/package,
Fixed already...

2020-04-17 17:58 UTC, merged